#!/usr/bin/env python3
"""Checks for the CLI verification slices.

  check_gcode.py diff BASE NEW          features off: identical apart from timestamps/stats
  check_gcode.py s4 FILE                Cartesian S4: non-planar layers, sane bounds, extrusion
  check_gcode.py polar CART POLAR       polar output reproduces the Cartesian path and extrusion
"""
import math
import re
import sys

WORD = re.compile(r'([A-Z])([-+]?[0-9]*\.?[0-9]+(?:[eE][-+]?[0-9]+)?)')
VOLATILE = re.compile(r'^; (generated by|model printing time|total estimated time|estimated printing time|'
                      r'HEADER_BLOCK|filament used|total filament|total layers count)|^M73 ', re.I)


def body(line):
    return line.split(';', 1)[0].strip()


def moves(path, axes):
    """Endpoints of G0/G1 moves: dict of axis -> value, plus 'e' (relative extrusion) and 'line'."""
    pos = {a: 0.0 for a in axes}
    seen = set()
    out = []
    in_start = True
    with open(path, errors='replace') as f:
        for n, raw in enumerate(f, 1):
            if 'MACHINE_START_GCODE_END' in raw or raw.startswith(';LAYER_CHANGE'):
                in_start = False
            if 'MACHINE_END_GCODE_START' in raw:
                break
            b = body(raw)
            if not b:
                continue
            words = dict((k, float(v)) for k, v in WORD.findall(b.upper()[b.find(' '):] if ' ' in b else ''))
            cmd = b.split()[0].upper()
            if cmd not in ('G0', 'G1'):
                continue
            for a in axes:
                if a in words:
                    pos[a] = words[a]
                    seen.add(a)
            # Before every axis has been set the position is unknown (a retract before the first move).
            out.append(dict(pos, e=words.get('E', 0.0), line=n, start=in_start, known=len(seen) == len(axes)))
    return out


CONFIG_LINE = re.compile(r'^; ([a-z0-9_]+) = ')


def cmd_diff(base, new):
    def lines(p):
        with open(p, errors='replace') as f:
            return [l.rstrip('\n') for l in f if not VOLATILE.search(l)]
    a, b = lines(base), lines(new)
    # Options added since the baseline appear only in the new config block: compare shared keys.
    keys = lambda ls: {m.group(1) for m in map(CONFIG_LINE.match, ls) if m}
    shared = keys(a) & keys(b)
    only = lambda ls: [l for l in ls if not (CONFIG_LINE.match(l) and CONFIG_LINE.match(l).group(1) not in shared)]
    print('config keys only in new:', sorted(keys(b) - keys(a)), 'only in base:', sorted(keys(a) - keys(b)))
    a, b = only(a), only(b)
    diffs = [(i, x, y) for i, (x, y) in enumerate(zip(a, b)) if x != y]
    print(f'{len(a)} vs {len(b)} lines, {len(diffs)} differing')
    for i, x, y in diffs[:10]:
        print(f'  {i}: {x!r}\n      {y!r}')
    return 0 if not diffs and len(a) == len(b) else 1


def cmd_s4(path):
    ms = [m for m in moves(path, 'XYZ') if not m['start']]
    ext = [m for m in ms if m['e'] > 0]
    if not ext:
        print('no extrusion')
        return 1
    # Layer = run of extrusions between ;LAYER_CHANGE markers.
    layers, cur = [], []
    marks = set()
    with open(path, errors='replace') as f:
        for n, l in enumerate(f, 1):
            if l.startswith(';LAYER_CHANGE'):
                marks.add(n)
    mark_lines = sorted(marks)
    import bisect
    by_layer = {}
    for m in ext:
        by_layer.setdefault(bisect.bisect(mark_lines, m['line']), []).append(m['Z'])
    spans = sorted(max(z) - min(z) for z in by_layer.values())
    nonplanar = sum(1 for s in spans if s > 0.05)
    xs, ys, zs = [m['X'] for m in ext], [m['Y'] for m in ext], [m['Z'] for m in ext]
    print(f'{len(ext)} extruding moves in {len(by_layer)} layers; {nonplanar} layers vary in Z by > 0.05 mm, '
          f'largest {spans[-1]:.2f} mm')
    print(f'bounds X {min(xs):.2f}..{max(xs):.2f} Y {min(ys):.2f}..{max(ys):.2f} Z {min(zs):.2f}..{max(zs):.2f}; '
          f'filament {sum(m["e"] for m in ms):.1f} mm')
    return 0 if nonplanar > 0 and min(zs) > 0 else 1


def cmd_polar(cart, polar, cx='100', cy='100', pivot='0', tilt_sign='1', tol='0.08'):
    """Machine moves back to the tool tip: undo the pivot compensation (radius and Z) with the
    physical tilt (tilt_sign * B, positive toward +radius), then the polar angle."""
    cx, cy, pivot, tilt_sign, tol = float(cx), float(cy), float(pivot), float(tilt_sign), float(tol)
    c = [m for m in moves(cart, 'XYZ') if not m['start']]
    p = [m for m in moves(polar, 'CXZB') if not m['start']]
    tips = []
    for m in p:
        if not m['known']:
            tips.append((math.inf, math.inf, math.inf))
            continue
        t = math.radians(tilt_sign * m['B'])
        r = m['X'] - pivot * math.sin(t)
        z = m['Z'] - pivot * (math.cos(t) - 1.)
        a = math.radians(m['C'])
        tips.append((cx + r * math.cos(a), cy + r * math.sin(a), z))
    j, missed, worst = 0, 0, 0.0
    for m in (m for m in c if m['known']):
        best, best_k = None, None
        # The next Cartesian endpoint must appear in order among the polar tips.
        for k in range(j, min(len(tips), j + 5000)):
            d = math.dist((m['X'], m['Y'], m['Z']), tips[k])
            if d < tol:
                # Polar moves subdivide the segment: follow it to the closest tip.
                best, best_k = d, k
                while best_k + 1 < len(tips):
                    d = math.dist((m['X'], m['Y'], m['Z']), tips[best_k + 1])
                    if d > best:
                        break
                    best, best_k = d, best_k + 1
                break
        if best_k is None:
            missed += 1
        else:
            worst = max(worst, best)
            j = best_k
    ec, ep = sum(m['e'] for m in c), sum(m['e'] for m in p)
    bs = [m['B'] for m in p]
    xs = [m['X'] for m in p]
    print(f'{len(c)} Cartesian moves -> {len(p)} polar moves; {missed} Cartesian endpoints not found in order '
          f'(tol {tol}), worst match {worst:.4f} mm')
    print(f'filament {ec:.4f} -> {ep:.4f} mm; B {min(bs):.1f}..{max(bs):.1f} deg; X {min(xs):.1f}..{max(xs):.1f} mm; '
          f'C {min(m["C"] for m in p):.1f}..{max(m["C"] for m in p):.1f} deg')
    return 0 if missed == 0 and abs(ec - ep) < 1e-3 * max(1.0, ec) else 1


if __name__ == '__main__':
    mode = sys.argv[1]
    sys.exit({'diff': cmd_diff, 's4': cmd_s4, 'polar': cmd_polar}[mode](*sys.argv[2:]))
